# Define list of hosts. Notice that "xrv" has a "file_system" key that
# "csr" does not. Netmiko can sometimes auto-discover file sytems.
---
host_list:
  - name: R1
    vrf_cmd: "show running-config | section vrf_def"
    platform: ios
  - name: R2
    vrf_cmd: "show running-config vrf"
    platform: iosxr
    file_system: "disk0:"
