---
host_list:
  - name: csr
    platform: ios
    filter: "<native><vrf></vrf></native>"
    edit_target: running
    operation: ~
  - name: xrv
    platform: iosxr
    filter: '<vrfs xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-infra-rsi-cfg"></vrfs>'
    edit_target: candidate
    operation: replace
