---
host_list:
  - name: R1
    platform: ios
    filter: "<native><vrf></vrf></native>"
    edit_target: running
  - name: R2
    platform: iosxr
    filter: >-
      <vrfs xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-infra-rsi-cfg"></vrfs>
    edit_target: candidate
    operation: replace
