---
CSR:
  hostname: csr
  groups:
    - ios
  data:
    vrfs:
      - name: "TEST"
        description: "python automation testing"
        rd: "7:100"
        route_import:
          - "7:6"  # optional comment here
          - "7:8"  # optional comment here
          - "7:10"  # optional comment here
        route_export: []

XRV:
  hostname: xrv
  groups:
    - iosxr
  data:
    vrfs:
      - name: "TEST"
        description: "python automation testing"
        rd: "7:100"
        route_import:
          - "7:2"  # optional comment here
          - "7:6"  # optional comment here
          - "7:10"  # optional comment here
          - "7:333"  # optional comment here
          - "7:555"  # optional comment here
        route_export: []
