---
CSR:
  hostname: csr
  groups:
    - ios
  data:
    body:
      vrf:
        definition:
          - address-family:
              ipv4: {}
              ipv6: {}
            description: "CHEMICAL ENGINEERING FIRM"
            name: "CHEMICAL"
            rd: "65000:2"
            route-target:
              export:
                - asn-ip: "65000:2"
              import:
                - asn-ip: "65000:2"
          - address-family:
              ipv4: {}
              ipv6: {}
            description: "CHEMICAL ENGINEERING MANAGER"
            name: "CHEM_MGMT"
            rd: "65000:3"
            route-target:
              export:
                - asn-ip: "65000:3"
              import:
                - asn-ip: "65000:4"
          - address-family:
              ipv4: {}
              ipv6: {}
            description: "POLICE DEPARTMENT"
            name: "POLICE"
            rd: "65000:1"
            route-target:
              export:
                - asn-ip: "65000:1"
              import:
                - asn-ip: "65000:1"



#XRV:
#  hostname: csr
#  groups:
#    - iosxr
#  data:
#    vrfs:
#      - name: "TEST"
#        description: "python automation testing"
#        rd: "7:100"
#        route_import:
#          - "7:2"  # optional comment here
#          - "7:6"  # optional comment here
#          - "7:8"  # optional comment here
#          - "7:10"  # optional comment here
#        route_export: []
